language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

# https://github.com/travis-ci/travis-ci/issues/9069
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
cache: pip

install:
    - pip install flake8

script:
    - flake8 aioreloader/ setup.py

deploy:
    provider: pypi
    user: and800
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    on:
        tags: true
        python: "3.6"
